title: "turpin.dev"
description: "Sometimes more is more"
author: "Dean Turpin"
# email: tbd
# url: "https://your-username.github.io"
# baseurl: "" # Change to "/project-name" if it's a project site

# Site settings
# theme: minima
theme: architect
# theme: minima
# theme: minima
# theme: minima
# theme: minima
# theme: minima
# remote_theme: aterenin/minima-reboot
# paginate: 10
# paginate_path: "/page:num/"
minima:
  skin: dark
  date_format: "%b %-d, %Y"

# Plugins
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag

# Permalink settings
# permalink: /:categories/:year/:month/:day/:title/

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
